name: dart_cmder
description: This Dart package offers a streamlined and intuitive interface for building powerful Command Line Interface (CLI) applications.
version: 0.0.5-prerelease

homepage: https://github.com/nikosportolos/dart_cmder
repository: https://github.com/nikosportolos/dart_cmder
documentation: https://github.com/nikosportolos/dart_cmder
issue_tracker: https://github.com/nikosportolos/dart_cmder/issues

environment:
  sdk: '>=3.1.0 < 4.0.0'

dependencies:
  ansix: ^0.3.2
  args: ^2.4.2
  meta: ^1.12.0
  path: ^1.9.0
  trace: ^0.0.6-prerelease

dev_dependencies:
  lints: ^4.0.0
  mocktail: ^1.0.3
  test: ^1.25.1

screenshots:
  - description: 'This is a sample usage of dart_cmder'
    path: assets/images/example.webp

topics:
  - cli
  - console
  - command
  - interface
  - terminal
