name: dart_cmder
description: This Dart package offers a streamlined and intuitive interface for building powerful Command Line Interface (CLI) applications.
version: 0.0.1-prerelease

homepage: https://github.com/nikosportolos/dart_cmder
repository: https://github.com/nikosportolos/dart_cmder
documentation: https://github.com/nikosportolos/dart_cmder
issue_tracker: https://github.com/nikosportolos/dart_cmder/issues

environment:
  sdk: '>=3.1.0 < 4.0.0'

dependencies:
  ansix: ^0.2.2
  args: ^2.4.2
  meta: ^1.10.0
  path: ^1.8.3
  trace: ^0.0.3-prerelease

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6

screenshots:
  - description: 'This is a sample usage of dart_cmder'
    path: assets/images/example.webp

topics:
  - cli
  - console
  - command
  - interface
  - terminal
