name: dart_cmder
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 < 4.0.0'

dependencies:
  ansix:
    git:
      url: https://github.com/nikosportolos/ansix
  args: ^2.4.2
  meta: ^1.10.0
  trace:
    git:
      url: https://github.com/nikosportolos/trace
      ref: develop

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
